Hotfix register form
ThomasKleinhans/rond-point pull request #24
Opened 2021-09-24 13:15 UTC by bmangeat

2021-09-24 13:25 UTC, ThomasKleinhans requested changes

2021-09-24 13:25 UTC, ThomasKleinhans commented on src/pages/Auth/Register.page.vue
> +        @click="onSubmit"
Il y a déjà un event @submit sur le form, ça va envoyer le form 2 fois

2021-09-24 13:25 UTC, ThomasKleinhans commented on src/store/modules/auth.js
> +      .then( ( response ) => this.$fb.addUserData( response.user.uid, firstName, lastName, email )
Faut modifier les données envoyées à la bdd si on veut une entrée firstname et lastname

2021-09-24 16:18 UTC, bmangeat commented on src/pages/Auth/Register.page.vue
> +        @click="onSubmit"
Le bouton est en dehors du form c'est pour ça

2021-09-24 16:19 UTC, bmangeat commented on src/store/modules/auth.js
> +      .then( ( response ) => this.$fb.addUserData( response.user.uid, firstName, lastName, email )
Il faudra ces infos dans le profil, après on peut remettre name et retirer dans le profil la distinction. Comme tu veux, ça peut aussi marcher

2021-09-25 09:24 UTC, ThomasKleinhans commented on src/pages/Auth/Register.page.vue
> +        @click="onSubmit"
Du coup enlever le @submit plut haut ?

2021-09-25 09:25 UTC, ThomasKleinhans commented on src/store/modules/auth.js
> +      .then( ( response ) => this.$fb.addUserData( response.user.uid, firstName, lastName, email )
Non non on peut laisser mais dans ce cas faut jsute mettre à jour les infos envoyées à Firebase dans auth.js

2021-12-28 14:20 UTC, merged